


#define RCC_APB1ENR	 *((unsigned int*)(0x40023800+0x40))
#define UART_BASE_ADDRESS	0x40004400 // uart2
#define UART_REG(BASE_ADDRESS,OFFSET) 	*((unsigned int*)(BASE_ADDRESS+OFFSET))



	/* Register Definition */
#define GPIOA_AFRL UART_REG(0x40020000,0x20)


#define USART_SR	UART_REG(UART_BASE_ADDRESS,0x00)
#define USART_DR	UART_REG(UART_BASE_ADDRESS,0x04)
#define USART_BRR	UART_REG(UART_BASE_ADDRESS,0x08)
#define USART_CR1	UART_REG(UART_BASE_ADDRESS,0x0C)
#define USART_CR2	UART_REG(UART_BASE_ADDRESS,0x10)
#define USART_CR3	UART_REG(UART_BASE_ADDRESS,0x14)
#define USART_GTPR	UART_REG(UART_BASE_ADDRESS,0x18)
